# Generated by Django 3.1.1 on 2021-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
    ]
